### ISSUE TITLE
Migrate Teaching Materials

### ISSUE THREAD

**Issue by ghutchis** [Avogadro/two.avogadro.cc#23]
Even if the screenshots are old, it would be good to migrate https://avogadro.cc/teaching/

**Comment by JGrantHill** [comment]
Would the plan be to add a "Teach" item to the menu bar in https://two.avogadro.cc? 

If so, I could try to work on this. Are there any guideline for screenshots (size etc) if I wanted to replace them with newer ones?

**Comment by ghutchis** [comment]
Yes, absolutely. I'm struggling a bit with how many items I can add to the top header, but I definitely want a "Teach" section. There's actually someone who wrote a full textbook.

No particular guidelines on size, but generally 400-600 px is a useful width. In some cases, downsizing by 75% can still be useful.

**Comment by JGrantHill** [comment]
I have migrated the materials in PR #55. The screenshots and instructions are stale from Avogadro 1, but I have inserted a warning to that effect at the Teach top level.

I'm not sure who contributed the original materials, or the best way to attribute them.

**Comment by ghutchis** [comment]
I'll take a look - I know I have attributions somewhere for "Romanov"

**Comment by ghutchis** [comment]
I'm going to leave this open as a reminder to find the attribution.

**Comment by ghutchis** [comment]
Okay, I absolutely cannot find the attribution - it was from the Avogadro wiki.

Hopefully before we release 2.0 I can find the original author.
