### ISSUE TITLE
Wrong nitrogen valence

### ISSUE THREAD

**Issue by fmentink** [Avogadro/two.avogadro.cc#26]
Description:
Open Avogadro, draw a molecule with just single bonds attached to a nitrogen, e.g. N(CH3)3. Later add one double bond in between N and one C.
The nitrogen then obtains 5 bonds. See attached screenshot

Version tested: 1.95.1 debian package and 1.97 AppImage, Linux Ubuntu 20.22

https://dl.dropboxusercontent.com/s/6w8m0kop770tbt1/Screenshot%20from%202022-12-01%2009-33-01.png?dl=0

**Comment by ghutchis** [comment]
This is a repository for the website documentation.

I think you want to submit at https://github.com/openchemistry/avogadrolibs/issues
